# CI de Nível 03 - Disparo após a conclusão de um pipeline

# Nom do nosso 'pipeline'
name: 'Execução por Deploy'

# Começar a configurar as regras de pipeline
# regras de disparo (gatilhos/triggers)
# gatilho de execução a partir de outro pipeline = workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# configura as tarefas/trabalhos dentro do pipeline = jobs
jobs:
  e2e-tests:
    #máquina que o job vai executar
    runs-on: ubuntu-latest

    # condicional
    # `${expressao}`
    # == comparação
    # coloca o if para validar se a pipeline manual foi executada com sucesso. se sim, executa os steps
    # se nao, nem executa a pipe 03-post-deploy

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #steps - passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do playwright
      - name: Instalando playwright
        run: yarn playwright install

      # Executar os testes e2e
      - name: Executando testes E2E
        run: yarn run e2e

      # o código abaixo executa no final da execução da pipeline vigente para fazer upload do arquivo de relatório de testes
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: status_report_test
          path: ./playwright-report
